SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "nuts_label" (gid serial PRIMARY KEY,
"icc" varchar(2),
"nuts_code" varchar(5),
"nuts_label" varchar(80));
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE1','Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE10','Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE100','Arr. de Bruxelles-Capitale / Arr. van Brussel-Hoofdstad');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE2','Vlaams Gewest');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE21','Prov. Antwerpen');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE211','Arr. Antwerpen');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE212','Arr. Mechelen');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE213','Arr. Turnhout');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE22','Prov. Limburg (B)');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE221','Arr. Hasselt');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE222','Arr. Maaseik');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE223','Arr. Tongeren');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE23','Prov. Oost-Vlaanderen');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE231','Arr. Aalst');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE232','Arr. Dendermonde');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE233','Arr. Eeklo');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE234','Arr. Gent');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE235','Arr. Oudenaarde');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE236','Arr. Sint-Niklaas');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE24','Prov. Vlaams-Brabant');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE241','Arr. Halle-Vilvoorde');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE242','Arr. Leuven');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE25','Prov. West-Vlaanderen');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE251','Arr. Brugge');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE252','Arr. Diksmuide');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE253','Arr. Ieper');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE254','Arr. Kortrijk');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE255','Arr. Oostende');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE256','Arr. Roeselare');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE257','Arr. Tielt');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE258','Arr. Veurne');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE3','Région Wallonne');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE31','Prov. Brabant Wallon');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE310','Arr. Nivelles');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE32','Prov. Hainaut');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE321','Arr. Ath');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE322','Arr. Charleroi');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE323','Arr. Mons');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE324','Arr. Mouscron');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE325','Arr. Soignies');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE326','Arr. Thuin');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE327','Arr. Tournai');
INSERT INTO "nuts_label" ("icc","nuts_code","nuts_label") VALUES ('BE','BE33','Prov. Liège');
